#!/usr/bin/env bash

git clone https://github.com/jaor/xmobar.git git-xmobar
git clone https://github.com/xmonad/xmonad.git git-xmonad
git clone https://github.com/xmonad/xmonad-contrib.git git-xmonad-contrib
